service: aws-serve-fake-zillow-comps

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  comps:
    handler: comps.comps
    events:
      - http:
          path: zcomps
          method: get
          cors: true
